use anyhow::Result;
use std::fs;
use std::path::Path;

use crate::analyzer::ProjectAnalysis;

pub fn generate(output_dir: &str, analysis: &ProjectAnalysis) -> Result<()> {
    fs::create_dir_all(output_dir)?;

    generate_agents_md(output_dir, analysis)?;
    generate_architecture_md(output_dir, analysis)?;
    generate_knowledge_md(output_dir, analysis)?;

    Ok(())
}

fn generate_agents_md(dir: &str, analysis: &ProjectAnalysis) -> Result<()> {
    let path = Path::new(dir).join("AGENTS.md");
    let mut md = String::new();

    md.push_str(&format!("# {}\n\n", analysis.name));
    md.push_str("## Project Overview\n\n");

    let lang_summary: Vec<String> = analysis
        .language_stats
        .iter()
        .map(|(lang, lines)| format!("{} ({} lines)", lang, lines))
        .collect();
    md.push_str(&format!("Languages: {}\n\n", lang_summary.join(", ")));
    md.push_str(&format!(
        "Files: {} | Total Lines: {} | Avg Lines/File: {}\n\n",
        analysis.file_stats.total_files,
        analysis.file_stats.total_lines,
        analysis.file_stats.avg_lines_per_file
    ));

    if !analysis.dependencies.is_empty() {
        md.push_str("## Dependencies\n\n");
        for dep in &analysis.dependencies {
            if let Some(ref v) = dep.version {
                md.push_str(&format!("- `{}` ({})\n", dep.name, v));
            } else {
                md.push_str(&format!("- `{}`\n", dep.name));
            }
        }
        md.push('\n');
    }

    md.push_str("## Directory Structure\n\n");
    md.push_str("```\n");
    for m in &analysis.modules {
        md.push_str(&format!(
            "{:<40} {}\n",
            m.path.display(),
            m.description
        ));
    }
    md.push_str("```\n\n");

    if !analysis.interfaces.is_empty() {
        md.push_str("## Public Interfaces\n\n");
        let mut by_module: Vec<(String, Vec<String>)> = Vec::new();
        let mut current_module = String::new();
        let mut items: Vec<String> = Vec::new();

        for iface in &analysis.interfaces {
            if iface.module != current_module {
                if !items.is_empty() {
                    by_module.push((current_module.clone(), items.clone()));
                    items.clear();
                }
                current_module = iface.module.clone();
            }
            items.push(format!(
                "- `{}` {} (line {})",
                iface.kind, iface.name, iface.line
            ));
        }
        if !items.is_empty() {
            by_module.push((current_module, items));
        }

        for (module, items) in by_module {
            md.push_str(&format!("### {}\n\n", module));
            for item in items {
                md.push_str(&item);
                md.push('\n');
            }
            md.push('\n');
        }
    }

    fs::write(path, md)?;
    Ok(())
}

fn generate_architecture_md(dir: &str, analysis: &ProjectAnalysis) -> Result<()> {
    let path = Path::new(dir).join("architecture.md");
    let mut md = String::new();

    md.push_str(&format!("# {} Architecture\n\n", analysis.name));

    md.push_str("## Language Distribution\n\n");
    md.push_str("| Language | Lines | Percentage |\n");
    md.push_str("|----------|-------|------------|\n");
    let total = analysis.file_stats.total_lines as f64;
    for (lang, lines) in &analysis.language_stats {
        let pct = if total > 0.0 {
            *lines as f64 / total * 100.0
        } else {
            0.0
        };
        md.push_str(&format!("| {} | {} | {:.1}% |\n", lang, lines, pct));
    }
    md.push('\n');

    md.push_str("## Module Map\n\n");
    for m in &analysis.modules {
        md.push_str(&format!("### `{}`\n", m.name));
        md.push_str(&format!("- Path: `{}`\n", m.path.display()));
        md.push_str(&format!("- Lines: {}\n", m.line_count));
        md.push_str(&format!("- Symbols: {}\n", m.symbols.len()));
        if !m.symbols.is_empty() {
            md.push_str("- Contents:\n");
            for sym in &m.symbols {
                let vis = if sym.is_public { "pub" } else { "priv" };
                md.push_str(&format!(
                    "  - {} {} {} (line {})\n",
                    vis, sym.kind, sym.name, sym.line
                ));
            }
        }
        md.push('\n');
    }

    fs::write(path, md)?;
    Ok(())
}

fn generate_knowledge_md(dir: &str, analysis: &ProjectAnalysis) -> Result<()> {
    let path = Path::new(dir).join("knowledge.md");
    let mut md = String::new();

    md.push_str(&format!("# {} Knowledge Base\n\n", analysis.name));
    md.push_str("This file is auto-generated by `gitmind sync`.\n\n");

    // Merge agents.md and architecture.md content
    md.push_str("---\n\n");

    // Agents section
    md.push_str("## Quick Reference\n\n");
    md.push_str(&format!(
        "**Project**: {} | **Files**: {} | **Lines**: {}\n\n",
        analysis.name, analysis.file_stats.total_files, analysis.file_stats.total_lines
    ));

    if !analysis.dependencies.is_empty() {
        md.push_str("### Key Dependencies\n\n");
        for dep in &analysis.dependencies {
            if let Some(ref v) = dep.version {
                md.push_str(&format!("- `{}` v{}\n", dep.name, v));
            } else {
                md.push_str(&format!("- `{}`\n", dep.name));
            }
        }
        md.push('\n');
    }

    md.push_str("### All Public APIs\n\n");
    md.push_str("```text\n");
    for iface in &analysis.interfaces {
        md.push_str(&format!(
            "{}.{}: {} (line {})\n",
            iface.module, iface.name, iface.kind, iface.line
        ));
    }
    md.push_str("```\n");

    fs::write(path, md)?;
    Ok(())
}
